# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fayette Fresh
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Fayette Fresh is a project that aims to celebrate Fayette County,
  PA—for locals <em>and</em> visitors—by highlighting the food, art,
  commerce, and community that you find here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://billtalkington.github.io" # the base hostname & protocol for your site
facebook_username: FayetteFresh
twitter_username: FayetteFresh

# Build settings
markdown: kramdown
encoding: utf-8

# Google services
google_analytics: UA-65201101-2
