# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fayette Fresh
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Fayette Fresh is a Fayette County, PA based blog focused on 
  local food, culture, commerce, and ideas. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://billtalkington.github.io" # the base hostname & protocol for your site
facebook_username: FayetteFresh
twitter_username: FayetteFresh
#github_username: 

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-65201101-2
